FILESEXTRAPATHS:prepend := "${THISDIR}/linux-yocto-dev:"

KMACHINE:odroid-c1 = "odroid-c1"
KMACHINE:odroid-c2 = "odroid-c2"
KMACHINE:odroid-xu3 = "odroid-xu3"
KMACHINE:odroid-xu4 = "odroid-xu4"
KMACHINE:odroid-xu3-lite = "odroid-xu3-lite"
KMACHINE:odroid-hc1 = "odroid-hc1"
KMACHINE:odroid-h2 = "odroid-h2"
KMACHINE:odroid-n2 = "odroid-n2"

SRC_URI:append = " file://odroid-kmeta;type=kmeta;name=odroid-kmeta;destsuffix=odroid-kmeta"

COMPATIBLE_MACHINE:odroid-c1 = "odroid-c1"
COMPATIBLE_MACHINE:odroid-c2 = "odroid-c2"
COMPATIBLE_MACHINE:odroid-xu3 = "odroid-xu3"
COMPATIBLE_MACHINE:odroid-xu4 = "odroid-xu4"
COMPATIBLE_MACHINE:odroid-xu3-lite = "odroid-xu3-lite"
COMPATIBLE_MACHINE:odroid-hc1 = "odroid-hc1"
COMPATIBLE_MACHINE:odroid-h2 = "odroid-h2"
COMPATIBLE_MACHINE:odroid-n2 = "odroid-n2"
